### PR TITLE
Fix whitespace in "Shiny" and "Egg" on csv export and added Experience to the export

### PR DESCRIPTION
**Pull request by ZeroEcks**
The spaces are useless and make it hard to modify the csv programically.

There is no reason not to include exp in the export of the CSV.

### CODE REVIEW

**Comment by Cu3PO42** [comment]
Will merge the removal of whitespace, but not adding experience, because it is a breaking change. Will add it to a later milestone. Please create a new PR with only the whitespace changes.

**Comment by ZeroEcks** [comment]
What does it break, sounds good though.

**Comment by Cu3PO42** [comment]
It breaks any scripts that parse the CSV output (properly).

**Comment by ZeroEcks** [comment]
I thought of your relying on the exact number of columns your doing it wrong

**Pull request closed without merging**
